interface ExportData {
  useCaseName: string;
  workflowName: string;
  prospects: number;
  emailsPerProspect: number;
  actions: Array<{
    action: string;
    credits_per_unit: number;
    description: string;
  }>;
  totalCredits: number;
  totalUsd: number;
  creditPerUsd: number;
  useCaseId: string;
}

export function exportQuote(data: ExportData) {
  const { 
    useCaseName, 
    workflowName, 
    prospects, 
    emailsPerProspect, 
    actions, 
    totalCredits, 
    totalUsd, 
    creditPerUsd,
    useCaseId 
  } = data;

  const getUnitLabels = (useCaseId: string) => {
    switch (useCaseId) {
      case 'ai-sdr':
        return { unit1: 'prospects', unit2: 'emails' };
      case 'ai-marketer':
        return { unit1: 'blog posts', unit2: 'social posts' };
      case 'ai-customer-service':
        return { unit1: 'tickets', unit2: 'follow-ups' };
      case 'ai-knowledge-search':
        return { unit1: 'searches', unit2: 'documents' };
      case 'ai-hr-support':
        return { unit1: 'queries', unit2: 'follow-ups' };
      default:
        return { unit1: 'units', unit2: 'actions' };
    }
  };

  const unitLabels = getUnitLabels(useCaseId);
  const totalActions = prospects * emailsPerProspect;
  const costPerProspect = totalUsd / prospects;
  const costPerAction = totalUsd / totalActions;
  const currentDate = new Date().toLocaleDateString();

  const calculateActionCredits = (action: any) => {
    let multiplier = prospects;
    if (action.action.toLowerCase().includes('email') || 
        action.action.toLowerCase().includes('follow-up') ||
        action.action.toLowerCase().includes('social media') ||
        action.action.toLowerCase().includes('query') ||
        action.action.toLowerCase().includes('response')) {
      multiplier = prospects * emailsPerProspect;
    }
    return action.credits_per_unit * multiplier;
  };

  const content = `
LYZR AI CREDITS CALCULATOR - CAMPAIGN QUOTE
Generated on: ${currentDate}

==================================================
CAMPAIGN OVERVIEW
==================================================
Campaign Type: ${useCaseName} - ${workflowName}
Target ${unitLabels.unit1}: ${prospects.toLocaleString()}
${unitLabels.unit2} per ${unitLabels.unit1.slice(0, -1)}: ${emailsPerProspect}
Total Actions: ${totalActions.toLocaleString()}

==================================================
COST BREAKDOWN
==================================================
${actions.map(action => {
  const actionCredits = calculateActionCredits(action);
  const actionUsd = actionCredits * creditPerUsd;
  const multiplierText = action.action.toLowerCase().includes('email') || 
                        action.action.toLowerCase().includes('follow-up') ||
                        action.action.toLowerCase().includes('social media') ||
                        action.action.toLowerCase().includes('query') ||
                        action.action.toLowerCase().includes('response')
    ? `${prospects} ${unitLabels.unit1} × ${emailsPerProspect} ${unitLabels.unit2}`
    : `${prospects} ${unitLabels.unit1}`;
  
  return `${action.action}:
  • ${action.credits_per_unit} credits × ${multiplierText}
  • Total: ${actionCredits.toLocaleString()} credits ($${actionUsd.toFixed(2)})
  • Description: ${action.description}`;
}).join('\n\n')}

==================================================
TOTAL CAMPAIGN COST
==================================================
Total Credits Required: ${totalCredits.toLocaleString()}
Total USD Cost: $${totalUsd.toFixed(2)}

Cost per ${unitLabels.unit1.slice(0, -1)}: $${costPerProspect.toFixed(3)}
Cost per action: $${costPerAction.toFixed(3)}

==================================================
ASSUMPTIONS & NOTES
==================================================
• Credit rate: ${creditPerUsd} USD per credit
• Pricing is based on synthetic demo data
• Actual marketplace pricing may vary
• Campaign timeline estimate: 2-3 weeks
• Expected response rate: 15-25% (for sales campaigns)

==================================================
NEXT STEPS
==================================================
1. Review campaign parameters and adjust if needed
2. Confirm budget allocation for ${totalCredits.toLocaleString()} credits
3. Set up campaign monitoring and success metrics
4. Launch campaign with Lyzr AI automation

For questions or support, contact your Lyzr AI representative.

Generated by Lyzr AI Credits Calculator Demo
Visit: https://lyzr.ai
`.trim();

  // Create and download the file
  const blob = new Blob([content], { type: 'text/plain' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `lyzr-campaign-quote-${useCaseName.toLowerCase().replace(/\s+/g, '-')}-${currentDate.replace(/\//g, '-')}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
}